INSERT INTO faculties (faculty_name)
VALUES
('Faculty of Arts'),
('Cumming School of Medicine'),
('School of Architecture, Planning and Landscape'),
('Faculty of Graduate Studies'),
('Haskayne School of Business'),
('Faculty of Kinesiology'),
('Faculty of Law'),
('Faculty of Nursing'),
('Faculty of Nursing (Qatar)'),
('Schulich School of Engineering'),
('Faculty of Science'),
('Faculty of Social Work'),
('Faculty of Veterinary Medicine'),
('Werklund School of Education'),
('School of Public Policy');

INSERT INTO majors (major_name, faculty_id)
VALUES
('Accounting (BComm)', 5),
('Actuarial Science (BSc)', 11),
('Anthropology (BA)', 1),
('Anthropology (BSc)', 11),
('Archaeology (BA)', 1),
('Archaeology (BSc)', 1),
('Architecture (MArch)', 3),
('Art History (BA)', 1),
('Astrophysics (BSc)', 11),
('Biochemistry (BSc)', 11),
('Bioinformatics (BHSc)', 2),
('Biological Sciences (BSc)', 11),
('Biomechanics (BSc)', 11),
('Biomedical Engineering (BSc in Eng)', 10),
('Biomedical Sciences (BHSc)', 2),
('Business (BComm)', 5),
('Business Analytics (BComm)', 5),
('Business Technology Management', 5),
('Cellular, Molecular and Microbial Biology (BSc)', 11),
('Chemical Engineering (BSc in Eng)', 10),
('Chemistry (BSc)', 11),
('Civil Engineering (BSc in Eng)', 10),
('Communication and Media Studies (BA/BCMS)', 1),
('Community Rehabilitation (BCR)', 2),
('Computer Science (BSc)', 11),
('Dance (BA/BFA)', 1),
('Data Science (BSc)', 11),
('Design in City Innovation (BDCI)', 3),
('Drama (BFA)', 1),
('Economics (BA)', 5),
('Education (BEd)', 14),
('Electrical Engineering (BSc in Eng)', 10),
('Energy Engineering (BSc in Eng)', 10),
('Energy Science (BSc)', 11),
('Engineering (common first year) (BSc in Eng)', 10),
('Engineering Physics (BSc in Eng)', 10),
('English (BA)', 1),
('Entrepeneurship and Innovation (BComm)', 5),
('Environmental Design (MEDes)', 3),
('Environmental Science (BSc)', 11),
('Exercise and Health Physiology (BSc)', 6),
('Film Studies (BA/BFS)', 1),
('Finance (BComm)', 5),
('French (BA)', 1),
('Gender and Sexuality Studies (BA)', 1),
('Geography (BA)', 1),
('Geography (BSc)', 1),
('Geology (BSc)', 11),
('Geomatics Engineering (BSc in Eng)', 10),
('Geophysics (BSc)', 11),
('Global Development Studies (BA)', 1),
('Health and Society (BHSc)', 2),
('History (BA)', 1),
('International Business Strategy (BComm)', 5),
('International Indigenous Studies (BA)', 1),
('International Relations (BA)', 1),
('Kinesiology (Bkin/BSc)', 6),
('Landscape Architecture (MLA)', 3),
('Language and Culture (BA)', 1),
('Law (JD)', 7),
('Law and Society (BA)', 1),
('Leadership and Coaching (BKin)', 6),
('Linguistics (BA)', 1),
('Linguistics and Language (BA)', 1),
('Marketing (BComm)', 5),
('Mathematics (BSc)', 11),
('Mechanical Engineering (BSc in Eng)', 10),
('Medicine (MD)', 2),
('Motor and Psychosocial Aspects of Movement (Bkin/BSc)', 6),
('Multidisciplinary Studies (BA)', 1),
('Music (BA)', 1),
('Music (BMus)', 1),
('Natural Sciences (BSc)', 11),
('Neuroscience (BSc)', 11),
('Nursing (Indigenous Community Route) (BScN)', 8),
('Nursing (Medicine Hat) (BScN)', 8),
('Nursing (Rural Community Route) (BScN)', 8),
('Nursing (year 1) (BScN)', 8),
('Nursing (year 2) (BScN)', 8),
('Oil and Gas engineering (BSc in Eng)', 10),
('Operations and Supply Chain Management (BComm)', 5),
('Organizational Behaviour and Human Resources (BComm)', 5),
('Philosophy (BA)', 1),
('Physics (BSc)', 11),
('Planning (MPlan)', 3),
('Plant Biology (BSc)', 11),
('Political Science (BA)', 1),
('Psychology (BA)', 1),
('Psychology (BSc)', 1),
('Risk Management (BComm)', 5),
('Social Work (BSW)', 12),
('Sociology (BA)', 1),
('Software Engineering (BSc in Eng)', 10),
('Statistics (BSc)', 11),
('Sustainable Systems Engineering (BSc in Eng)', 10),
('Undeclared (Arts)', 1),
('Urban Studies (BA)', 1),
('Veterinary Medicine (DVM)', 13),
('Visual Studies (BFA)', 1),
('Zoology (BSc)', 11);

INSERT INTO tags (tag_category, tag_name)
VALUES
('Entertainment', 'Gaming'),
('Entertainment', 'Music'),
('Entertainment', 'Movies'),
('Entertainment', 'TV Shows'),
('Entertainment', 'Anime'),
('Entertainment', 'Reading'),
('Entertainment', 'Writing'),
('Entertainment', 'Art & Design'),
('Entertainment', 'Photography'),
('Entertainment', 'Videography'),
('Entertainment', 'Fashion'),
('Entertainment', 'Collecting'),
('Entertainment', 'DIY & Crafts'),
('Academics', 'Technology'),
('Academics', 'Science'),
('Academics', 'Engineering'),
('Academics', 'Business'),
('Academics', 'Economics'),
('Academics', 'Literature'),
('Academics', 'Psychology'),
('Academics', 'Philosophy'),
('Academics', 'History'),
('Academics', 'Mathematics'),
('Academics', 'Languages'),
('Academics', 'Education'),
('Lifestyle', 'Sports'),
('Lifestyle', 'Fitness'),
('Lifestyle', 'Health & Wellness'),
('Lifestyle', 'Running'),
('Lifestyle', 'Gym'),
('Lifestyle', 'Yoga'),
('Lifestyle', 'Hiking'),
('Lifestyle', 'Dance'),
('Lifestyle', 'Esports'),
('Lifestyle', 'Outdoor Activities'),
('Social & Cultural', 'Politics'),
('Social & Cultural', 'Current Events'),
('Social & Cultural', 'Culture'),
('Social & Cultural', 'Travel'),
('Social & Cultural', 'Foodie'),
('Social & Cultural', 'Sustainability'),
('Social & Cultural', 'Environment'),
('Social & Cultural', 'Social Justice'),
('Social & Cultural', 'Entrepreneurship'),
('Social & Cultural', 'Community Service'),
('Personality', 'Minimalism'),
('Personality', 'Aesthetics'),
('Personality', 'Productivity'),
('Personality', 'Creativity'),
('Personality', 'Mindfulness'),
('Personality', 'Self-Improvement'),
('Personality', 'Humor & Memes'),
('Personality', 'Pop Culture'),
('Personality', 'Self-Care'),
('Personality', 'Journaling'),
('Tech', 'AI / Machine Learning'),
('Tech', 'Coding'),
('Tech', 'Web Development'),
('Tech', 'Startups'),
('Tech', 'Crypto / Blockchain'),
('Tech', 'UI/UX Design'),
('Tech', 'Data Science'),
('Tech', 'Robotics'),
('Tech', 'Cybersecurity'),
('Tech', 'Hardware / Gadgets'),
('Campus Life', 'Clubs & Events'),
('Campus Life', 'Volunteering'),
('Campus Life', 'Student Leadership'),
('Campus Life', 'Campus Life'),
('Campus Life', 'Study Spots'),
('Campus Life', 'Research'),
('Campus Life', 'Residence Life'),
('Campus Life', 'Networking'),
('Campus Life', 'Career Development'),
('Campus Life', 'Mental Health');

INSERT INTO resources (resource_category, resource_name, resource_url)
VALUES
('Academic', 'UofC Website', 'https://www.ucalgary.ca'),
('Academic', 'Portal', 'https://portal.my.ucalgary.ca/psp/paprd/?cmd=login&languageCd=ENG&'),
('Academic', 'D2L', 'https://d2l.ucalgary.ca/d2l/home'),
('Academic', 'Bookings', 'https://library.ucalgary.ca/services/bookings'),
('Academic', 'Study Space Map', 'https://ucalgary-gs.maps.arcgis.com/apps/webappviewer/index.html?id=d86b320c2564480aaf914130c44ec6b8'),
('Academic', 'Elevate', 'https://elevate.ucalgary.ca/home.htm'),
('Academic', 'SU Clubs', 'https://suuofc.campuslabs.ca/engage/'),
('Academic', 'UC Reddit', 'https://www.reddit.com/r/UCalgary/'),
('Academic', 'GPA Calculator', 'https://gradecalc.info/ca/ab/ucalgary/gpa_calc.pl'),
('Life & Wellness', 'Open Gym Drop-in Schedule', 'https://schedules.active-living.ucalgary.ca/alcalendargymtimes.aspx'),
('Life & Wellness', 'Active Living', 'https://active-living.ucalgary.ca'),
('Life & Wellness', 'Active Living Rentals/Bookings', 'https://active-living.ucalgary.ca/rental-bookings'),
('Life & Wellness', 'UofC Mental Health Services', 'https://ucalgary.ca/wellness-services/services/mental-health-services'),
('Life & Wellness', 'UofC Medical Services', 'https://ucalgary.ca/wellness-services/services/medical-services'),
('Life & Wellness', 'UofC Peer Support', 'https://ucalgary.ca/wellness-services/services/mental-health-services/peer-support'),
('Services', 'Campus Map & Room Finder', 'https://www.ucalgary.ca/about-ucalgary/our-campuses/campus-maps-and-room-finder'),
('Services', 'Campus Security', 'https://www.ucalgary.ca/risk/campus-security/contact-us'),
('Services', 'Parking Map', 'https://www.ucalgary.ca/ancillary/parking/parking-permits/find-parking'),
('Services', 'Parking Rates', 'https://www.ucalgary.ca/ancillary/parking/parking-permits/parking-rates-0'),
('Services', 'Residence Services', 'https://www.ucalgary.ca/ancillary/residence'),
('Services', 'Unicard Services', 'https://www.ucalgary.ca/ancillary/unicard'),
('Services', 'Meal Plans', 'https://www.ucalgary.ca/ancillary/unicard/use-card/meal-plan'),
('Tools', 'Free GitHub Pro for Students', 'https://github.com/education/students'),
('Tools', 'Free Notion Plus for Students', 'https://www.notion.com/help/notion-for-education'),
('Tools', 'Spotify Student Discount', 'https://www.spotify.com/ca-en/student/'),
('Tools', 'Apple Music Student Discount', 'https://offers.applemusic.apple/en-ca/student-offer#:~:text=Students%20save%20on%20Apple%20Music,student%20rate%20of%20%245.99%2Fmonth.');
